# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
