# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20160411_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uch_step', models.TextField(max_length=200)),
                ('uch_zvan', models.TextField(max_length=200)),
                ('dolgnost', models.TextField(max_length=200)),
                ('kval', models.TextField(max_length=200)),
                ('experience_all', models.IntegerField()),
                ('experience_spec', models.IntegerField()),
                ('experience_eaca', models.IntegerField()),
                ('disser_job', models.TextField(max_length=200)),
                ('sience_inter', models.TextField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
