# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTypeMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type_more', models.TextField(max_length=200)),
            ],
        ),
    ]
