# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_doctypemore'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_more',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.DocTypeMore'),
        ),
    ]
