# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160412_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DocStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DocSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='docfile',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='docfile',
            name='files',
        ),
        migrations.RemoveField(
            model_name='doctype',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type_more',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='year',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Files'),
        ),
        migrations.DeleteModel(
            name='DocFile',
        ),
        migrations.DeleteModel(
            name='DocTypeMore',
        ),
        migrations.AddField(
            model_name='docstructure',
            name='doc_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DocType'),
        ),
        migrations.AddField(
            model_name='docfield',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document'),
        ),
        migrations.AddField(
            model_name='docfield',
            name='doc_str',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DocStructure'),
        ),
        migrations.AddField(
            model_name='document',
            name='sub_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.DocSubType'),
        ),
    ]
