# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160414_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='abbr',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
