# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160414_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docstructure',
            old_name='doc_type_id',
            new_name='doc_type',
        ),
        migrations.AlterField(
            model_name='docstructure',
            name='type',
            field=models.CharField(default='string', max_length=50),
        ),
    ]
