# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160414_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docstructure',
            name='type',
        ),
    ]
