# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_docstructure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='docstructure',
            name='type',
            field=models.CharField(default='string', max_length=50),
        ),
    ]
