# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_docstructure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstructure',
            name='type',
            field=models.CharField(default='string', max_length=50, null=True),
        ),
    ]
