# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160414_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docfield',
            old_name='doc_id',
            new_name='document',
        ),
    ]
