# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160417_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docsubtype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DocSubType'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Files'),
        ),
    ]
